# status codes
SUCCESS_STATUS_CODE = 200
NO_CONTENT_STATUS_CODE = 204
BAD_REQUEST_STATUS_CODE = 400
FAIL_STATUS_CODE = 500
PARAMETER_VALIDATION = 1008
METHOD_NOT_ALLOWED_CODE = 405
INVALID_STATUS_CODE = 404
INVALID_INPUT_ERROR_CODE = 4001
WRONG_DATA_STATUS_CODE = 4002


# status
SUCCESS_STATUS = "SUCCESS"
FAIL_STATUS = "FAIL"

