# Generated by Django 2.2.16 on 2020-10-11 06:39

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consolole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('slug', django_extensions.db.fields.RandomCharField(blank=True, editable=False, include_digits=False, length=6, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rental_amount', models.FloatField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consolole.TrAssets')),
            ],
            options={
                'verbose_name': 'Contracts',
                'verbose_name_plural': 'contracts',
                'db_table': 'tr_contract',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=350)),
            ],
            options={
                'verbose_name': 'Contractor',
                'verbose_name_plural': 'contractor',
                'db_table': 'tr_contractor',
            },
        ),
        migrations.CreateModel(
            name='Maintainance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('monthly_rate', models.FloatField()),
                ('max_km', models.IntegerField(blank=True, max_length=5, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract')),
            ],
            options={
                'verbose_name': 'Maintainance',
                'verbose_name_plural': 'maintainance',
                'db_table': 'tr_maintainance',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('slug', django_extensions.db.fields.RandomCharField(blank=True, editable=False, include_digits=False, length=6, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True, null=True)),
                ('invoice_month', models.DateField()),
                ('Due_date', models.DateField()),
                ('invoice_amount', models.FloatField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'invoice',
                'db_table': 'tr_invoice',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Contractor'),
        ),
    ]
