# Generated by Django 2.2.16 on 2020-10-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintainance',
            name='max_km',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
