# Generated by Django 2.2.16 on 2020-10-11 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20201011_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_asset', to='consolole.TrAssets'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_invoice', to='contracts.Contract'),
        ),
        migrations.AlterField(
            model_name='maintainance',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_maintainance', to='contracts.Contract'),
        ),
    ]
