# Generated by Django 2.2.16 on 2020-10-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20201011_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
