# Generated by Django 2.2.16 on 2020-10-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20201018_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
